### ISSUE TITLE
Билд PlusicAPI

### ISSUE THREAD

**Issue by ArtArss** [Mega4oSS/PlusicAPI#9]
При билде командой gradle shadowJar билдится весь проект с либами кроме libs/aoh3.jar, в build.gradle.kts в зависимостях она указана:
![image](https://github.com/user-attachments/assets/caf03813-dfad-4185-876a-4c2213b83a57)
 Даже так пытался:
![image](https://github.com/user-attachments/assets/076565be-91ea-4e83-84b5-6fec0627397b)

**Comment by Mega4oSS** [comment]
я всё перепробовал уже, и никак не получится, так что ручками подмешивать придётся классы аоха.

**Comment by ArtArss** [comment]
> я всё перепробовал уже, и никак не получится, так что ручками подмешивать придётся классы аоха.

Я тоже так делаю))

**Comment by ArtArss** [comment]
Нет способа(

**Comment by Mega4oSS** [comment]
обидно кнш
